name: Windows Test

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          audience: ${{ secrets.TS_AUDIENCE }}
          tags: tag:ci

      - name: Keep runner alive
        shell: powershell
        run: |
          Write-Host "Windows runner is running..."
          Start-Sleep -Seconds 1800
