name: Windows Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Keep runner alive
        shell: powershell
        run: |
          Write-Host "Windows runner is running..."
          Start-Sleep -Seconds 1800
